# gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth

        image: fernandowi55/auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: eureka.client.service-url.defaultZone
          value: http://10.100.110.190:8761/eureka/

      
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
    
  
     
      
     

